version: '3'
services:

  redis-cluster-app:
    image: redis-cluster-app
    container_name: redis-cluster-app
    restart: always
    ports:
      - 8080:8080
    networks:
      - redis-cluster

  redis1:
    container_name: redis1
    image: redis:7.0.5
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster

  redis2:
    container_name: redis2
    image: redis:7.0.5
    ports:
      - "6380:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster

  redis3:
    container_name: redis3
    image: redis:7.0.5
    ports:
      - "6381:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster
  
  redis4:
    container_name: redis4
    image: redis:7.0.5
    ports:
      - "6382:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster
  
  redis5:
    container_name: redis5
    image: redis:7.0.5
    ports:
      - "6383:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster

  redis6:
    container_name: redis6
    image: redis:7.0.5
    ports:
      - "6384:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge


# version: '3'

# services:
#   redis-master:
#     image: redis
#     command: redis-server --appendonly yes
#     ports:
#       - "6379:6379"
#     networks:
#       - redis-cluster
#   redis-slave:
#     image: redis
#     command: redis-server --appendonly yes --slaveof redis-master 6379
#     networks:
#       - redis-cluster
#   redis-sentinel:
#     image: redis
#     command: redis-server --sentinel
#     environment:
#       - SENTINEL_DOWN_AFTER=10000
#       - SENTINEL_FAILOVER=10000
#     networks:
#       - redis-cluster

# networks:
#   redis-cluster:
#     driver: bridge


